[[ssh-keys]]
vault = "Private"
item = "Home"

[[ssh-keys]]
item = "Github"
vault = "Private"

[[ssh-keys]]
item = "SSH Key - prodagent"
vault = "Private"

[[ssh-keys]]
item = "Home RSA@4096"
vault = "Private"


